module StoreScraper
  module Itunes
    module Constants
      URL_PREFIX = 'https://itunes.apple.com'

      MAX_LIMIT  = 200

      # ref: https://affiliate.itunes.apple.com/resources/documentation/linking-to-the-itunes-music-store/
      COUNTRY_TABLE = {
        "ae" => "United Arab Emirates",
        "ag" => "Antigua & Barbuda",
        "ai" => "Anguilla",
        "am" => "Armenia",
        "ao" => "Angola",
        "ar" => "Argentina",
        "at" => "Austria",
        "au" => "Australia",
        "az" => "Azerbaijan",
        "bb" => "Barbados",
        "bd" => "Bangladesh",
        "be" => "Belgium",
        "bg" => "Bulgaria",
        "bh" => "Bahrain",
        "bm" => "Bermuda",
        "bn" => "Brunei",
        "bo" => "Bolivia",
        "br" => "Brazil",
        "bs" => "The Bahamas",
        "bw" => "Botswana",
        "by" => "Belarus",
        "bz" => "Belize",
        "ca" => "Canada",
        "ch" => "Switzerland",
        "ci" => "Cote DfIvoire",
        "cl" => "Chile",
        "cn" => "China",
        "co" => "Colombia",
        "cr" => "Costa Rica",
        "cy" => "Cyprus",
        "cz" => "Czech Republic",
        "de" => "Germany",
        "dk" => "Denmark",
        "dm" => "Dominica",
        "do" => "Dominican Rep.",
        "dz" => "Algeria",
        "ec" => "Ecuador",
        "ee" => "Estonia",
        "eg" => "Egypt",
        "es" => "Spain",
        "fi" => "Finland",
        "fr" => "France",
        "gb" => "UK",
        "gd" => "Grenada",
        "gh" => "Ghana",
        "gr" => "Greece",
        "gt" => "Guatemala",
        "gy" => "Guyana",
        "hk" => "Hong Kong",
        "hn" => "Honduras",
        "hr" => "Croatia",
        "hu" => "Hungary",
        "id" => "Indonesia",
        "ie" => "Ireland",
        "il" => "Israel",
        "in" => "India",
        "is" => "Iceland",
        "it" => "Italy",
        "jm" => "Jamaica",
        "jo" => "Jordan",
        "jp" => "Japan",
        "ke" => "Kenya",
        "kn" => "St. Kitts & Nevis",
        "kr" => "Korea, Republic Of",
        "kw" => "Kuwait",
        "ky" => "Cayman Islands",
        "kz" => "Kazakstan",
        "lb" => "Lebanon",
        "lc" => "St. Lucia",
        "li" => "Liechtenstein",
        "lk" => "Sri Lanka",
        "lt" => "Lithuania",
        "lu" => "Luxembourg",
        "lv" => "Latvia",
        "md" => "Moldova, Republic Of",
        "mg" => "Madagascar",
        "mk" => "Macedonia",
        "ml" => "Mali",
        "mo" => "Macau",
        "ms" => "Montserrat",
        "mt" => "Malta",
        "mu" => "Mauritius",
        "mv" => "Maldives",
        "mx" => "Mexico",
        "my" => "Malaysia",
        "ne" => "Niger",
        "ng" => "Nigeria",
        "ni" => "Nicaragua",
        "nl" => "Netherlands",
        "no" => "Norway",
        "np" => "Nepal",
        "nz" => "New Zealand",
        "om" => "Oman",
        "pa" => "Panama",
        "pe" => "Peru",
        "ph" => "Philippines",
        "pk" => "Pakistan",
        "pl" => "Poland",
        "pt" => "Portugal",
        "py" => "Paraguay",
        "qa" => "Qatar",
        "ro" => "Romania",
        "rs" => "Serbia",
        "ru" => "Russia",
        "sa" => "Saudi Arabia",
        "se" => "Sweden",
        "sg" => "Singapore",
        "si" => "Slovenia",
        "sk" => "Slovakia",
        "sn" => "Senegal",
        "sr" => "Suriname",
        "sv" => "El Salvador",
        "tc" => "Turks & Caicos",
        "th" => "Thailand",
        "tn" => "Tunisia",
        "tr" => "Turkey",
        "tt" => "Trinidad & Tobago",
        "tw" => "Taiwan",
        "tz" => "Tanzania",
        "ua" => "Ukraine",
        "ug" => "Uganda",
        "us" => "USA",
        "uy" => "Uruguay",
        "uz" => "Uzbekistan",
        "vc" => "St. Vincent & The Grenadines",
        "ve" => "Venezuela",
        "vg" => "British Virgin Islands",
        "vn" => "Vietnam",
        "ye" => "Yemen",
        "za" => "South Africa",
      }

      COUNTRIES = COUNTRY_TABLE.keys

      FEED_TYPES = %w(
        newapplications
        newfreeapplications
        newpaidapplications
        topfreeapplications
        topfreeipadapplications
        topgrossingapplications
        topgrossingipadapplications
        toppaidapplications
        toppaidipadapplications
      )

      DEFAULT_COUNTRY   = 'jp'
      DEFAULT_FEED_TYPE = 'topgrossingapplications'

      # ref: https://affiliate.itunes.apple.com/resources/documentation/genre-mapping/
      GENRE_ID_TABLE = {
        books: 6018,
        business: 6000,
        catalogs: 6022,
        education: 6017,
        entertainment: 6016,
        finance: 6015,
        food_drink: 6023,
        games: 6014,
        mzgenre_genrev: 6025,
        health_fitness: 6013,
        lifestyle: 6012,
        magazines_newspapers: 6021,
        medical: 6020,
        music: 6011,
        navigation: 6010,
        news: 6009,
        photo_video: 6008,
        productivity: 6007,
        reference: 6006,
        shopping: 6024,
        social_networking: 6005,
        sports: 6004,
        travel: 6003,
        utilities: 6002,
        weather: 6001,
        all: nil
      }
    end
  end
end
