---
- newapplications
- newfreeapplications
- newpaidapplications
- topfreeapplications
- topfreeipadapplications
- topgrossingapplications
- topgrossingipadapplications
- toppaidapplications
- toppaidipadapplications
