---
# ref: https://affiliate.itunes.apple.com/resources/documentation/genre-mapping/
books: 6018
business: 6000
catalogs: 6022
education: 6017
entertainment: 6016
finance: 6015
food_drink: 6023
games: 6014
mzgenre_genrev: 6025
health_fitness: 6013
lifestyle: 6012
magazines_newspapers: 6021
medical: 6020
music: 6011
navigation: 6010
news: 6009
photo_video: 6008
productivity: 6007
reference: 6006
shopping: 6024
social_networking: 6005
sports: 6004
travel: 6003
utilities: 6002
weather: 6001
all: 
